import { Hono } from 'hono';
import type { Context } from 'hono';
import { cors } from 'hono/cors';
import { OpenFeature } from '@openfeature/server-sdk';
import { FlagshipServerProvider } from '@cloudflare/flagship/server';

import artifactRoutes from './modules/artifacts/routes';
import appRoutes from './modules/apps/routes';
import builderRoutes from './modules/builder/routes';
import deploymentRoutes from './modules/deployments/routes';
import healthRoutes from './modules/health/routes';
import cloudflareIntegrationRoutes from './modules/integrations/cloudflare';
import githubIntegrationRoutes from './modules/integrations/github';
import portalRoutes from './modules/portal/routes';
import tenantRoutes from './modules/tenants/routes';
import workflowRunRoutes from './modules/workflow-runs/routes';
import { failure } from './lib/json';
import type { AppBindings } from './types/env'; // Corrected import

const app = new Hono<{ Bindings: AppBindings }>();

const corsOptions = {
  origin: (origin: string) => origin, // Allow any origin
  allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowHeaders: ['Content-Type', 'Authorization', 'X-Requested-With'],
  exposeHeaders: ['Content-Type'],
  maxAge: 86400,
  credentials: true,
};

// 1. CORS Middleware (Must be first)
app.use('*', cors(corsOptions));

// 2. Request logging middleware
app.use('*', async (c, next) => {
  console.log(`[Worker] Incoming Request: ${c.req.method} ${c.req.url}`);
  await next();
  console.log(`[Worker] Response: ${c.res.status}`);
});

// 3. Mock Bindings Middleware for local Node.js dev
const mockDbStore: Record<string, any> = {};

app.use('*', async (c, next) => {
  if (!c.env.DB) {
    console.log('[Local Dev] Injecting robust mock bindings');
    
    const mockPreparedQuery: any = {
      all: async () => {
        const values = Object.values(mockDbStore);
        return { results: values };
      },
      first: async () => {
        const values = Object.values(mockDbStore);
        // Try to find the exact match by id if we are doing a SELECT by id
        // This is a bit hacky but works for our mock
        return values.length > 0 ? values[0] : null;
      },
      run: async () => ({ success: true }),
      bind: function(...args: any[]) { 
        this.boundArgs = args; 
        return this; 
      },
      executeMock: async function() {
        if (this.sql?.includes('INSERT INTO builder_sessions')) {
          const [id, tenantId, appId, template, intent, status, createdAt, updatedAt] = this.boundArgs;
          mockDbStore[id] = { id, tenant_id: tenantId, app_id: appId, template, intent, status, created_at: createdAt, updated_at: updatedAt };
        } else if (this.sql?.includes('INSERT INTO tenants')) {
          const [id, name, slug] = this.boundArgs;
          mockDbStore[id] = { id, name, slug, created_at: new Date().toISOString() };
        } else if (this.sql?.includes('INSERT INTO apps')) {
          const [id, tenantId, name, slug] = this.boundArgs;
          mockDbStore[id] = { id, tenant_id: tenantId, name, slug, created_at: new Date().toISOString() };
        }
      }
    };

    (c.env as any).DB = {
      prepare: (sql: string) => {
        console.log(`[Local Dev] DB Prepare: ${sql}`);
        const query: any = { ...mockPreparedQuery, sql };
        query.run = async () => {
          await query.executeMock();
          return { success: true, changes: 1 }; // Simulate a change for successful run
        };
        return query;
      },
      batch: async (statements: any[]) => {
        console.log(`[Local Dev] DB Batch: ${statements.length} statements`);
        const results = [];
        for (const stmt of statements) {
          if (stmt.executeMock) {
            await stmt.executeMock();
          }
          results.push({ success: true, changes: 1 }); // Simulate a change for each successful run
        }
        return results;
      },
    };
    (c.env as any).FLAGS = {};
    (c.env as any).AI = {
      run: async (model: string, args: any) => {
        console.log(`[Local Dev] Mock AI run for model ${model}`);
        return {
          response: JSON.stringify({
            summary: "Mock generated UI component",
            files: [
              {
                path: "src/lib/components/ui/MockComponent.svelte",
                action: "create",
                content: "<script>\n  export let title = 'Mock Title';\n</script>\n\n<div class='p-4 border rounded shadow-sm bg-white'>\n  <h1 class='text-lg font-bold'>{title}</h1>\n  <p class='text-sm text-gray-500'>This is a mock component generated by the local builder.</p>\n</div>"
              }
            ],
            nextActions: ["Review the new mock component", "Test the builder UI"]
          })
        };
      }
    };

    // Mock STREAMER Durable Object namespace for local dev
    const mockStreamerNamespace: any = {
      idFromName: (name: string) => {
        console.log(`[Local Dev] Mock Streamer: idFromName(${name})`);
        return { name };
      },
      get: (id: any) => {
        console.log(`[Local Dev] Mock Streamer: get(${id?.name})`);
        return {
          fetch: async (request: Request) => {
            if (request.method === 'POST') {
              const body = await request.json();
              console.log(`[Local Dev] Mock Streamer: published event:`, JSON.stringify(body).slice(0, 200));
              return new Response('OK');
            }
            // SSE endpoint: return a simple stream
            const stream = new ReadableStream({
              start: (controller) => {
                controller.enqueue('data: {"type":"message","role":"assistant","content":"Connected to mock SSE stream"}\n\n');
                controller.close();
              }
            });
            return new Response(stream, {
              headers: {
                'Content-Type': 'text/event-stream',
                'Cache-Control': 'no-cache',
                'Connection': 'keep-alive',
              },
            });
          }
        };
      }
    };
    (c.env as any).STREAMER = mockStreamerNamespace;
  }
  await next();
});



let openFeatureInitialized = false;
let openFeatureInitialization: Promise<void> | null = null;

async function ensureOpenFeatureProvider(c: Context<{ Bindings: AppBindings }>) {
  if (openFeatureInitialized || openFeatureInitialization) {
    if (openFeatureInitialization) await openFeatureInitialization;
    return;
  }

  if (!c.env.FLAGS) {
    console.warn('Flagship binding (FLAGS) is missing. Skipping OpenFeature initialization.');
    return;
  }

  try {
    const provider = new FlagshipServerProvider({ binding: c.env.FLAGS });
    openFeatureInitialization = OpenFeature
      .setProviderAndWait(provider)
      .then(() => {
        openFeatureInitialized = true;
      })
      .catch((error) => {
        // Feature flags should not take down the operational API.
        console.error('Failed to initialize Flagship provider:', error);
      });

    await openFeatureInitialization;
  } catch (error) {
    console.error('Synchronous error during Flagship provider creation:', error);
  }
}

app.use(
  '/*',
  async (c, next) => {
    if (c.req.method !== 'OPTIONS') {
      await ensureOpenFeatureProvider(c);
    }

    await next();
  },
);

app.route('/', healthRoutes);
app.route('/api/health', healthRoutes);
app.route('/api/tenants', tenantRoutes);
app.route('/api/apps', appRoutes);
app.route('/api/deployments', deploymentRoutes);
app.route('/api/workflow-runs', workflowRunRoutes);
app.route('/api/integrations/github', githubIntegrationRoutes);
app.route('/api/integrations/cloudflare', cloudflareIntegrationRoutes);
app.route('/api/builder', builderRoutes);
app.route('/api/artifacts', artifactRoutes);
app.route('/api/portal', portalRoutes);

// Example endpoint to check a feature flag
app.get('/api/feature-check', async (c) => {
  const client = OpenFeature.getClient();
  const newBackendFeatureEnabled = await client.getBooleanValue('new-backend-feature', false, {
    targetingKey: 'some-user-id', // Replace with actual user ID or context
  });

  return c.json({ newBackendFeatureEnabled });
});

app.notFound((c) => {
  return failure(c, 404, 'Route not found.', {
    path: c.req.path,
  });
});

export default app;
export { SessionStreamer } from './modules/builder/streamer';
